include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - 'lib/data/serialization/*.g.dart'
    - 'lib/generated/**'
  strong-mode:
    implicit-casts: false

linter:
  rules:
    - camel_case_types